version: "3.7"
services:
  sentilo-server:
     image: luismariotti1/sentilo
    #  build: sentilo
     container_name: sentilo_servers
     depends_on:
      - "mongo-server"
      - "redis-server"
     ports:
        - 8081:8081
        - 8080:8080
  mongo-server:
     image: luismariotti1/sentilo-mongo
    #  build: mongo
     container_name: sentilo_mongo
     ports:
        - 27017:27017
  redis-server:
     image: redis:4.0.11
     container_name: sentilo_redis
     command: redis-server --requirepass sentilo
     ports:
       - 6379:6379
  opentsdb-server:
    build: opentsdb
    image: luismariotti1/sentilo-opentsdb
    container_name: sentilo_opentsdb
    ports:
      - 4242:4242
  elasticsearch-server:
    image: elasticsearch:8.2.0
    container_name: sentilo_elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 32768
        hard: 32768
    deploy:
      resources: 
        limits: 
          cpus: "0.50"  # Use at most 50% of one CPU core
          memory: 2000M  # Use at most 2 GB of RAM
    ports:
      - '9200:9200'
      - '9300:9300'
  kibana-server:
    container_name: sentilo_kibana
    image: kibana:8.2.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-server    
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
