services:
  # proxy 
  nginx-proxy:
    image: nginx:latest
    container_name: proxy_nginx
    ports:
      - 443:443
      - 80:80
      # - 8081:8081
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../certs/:/etc/nginx/certs/
    networks:
      - sentilo_network
  
networks:
  sentilo_network:
    name: sentilo_network
    external: true
